branch-defaults:
  master:
    environment: null
    group_suffix: null
  staging:
    environment: aion-mastery-node-staging
global:
  application_name: aion-mastery-node
  artifact: deploy.zip
  branch: master
  default_region: us-east-1
  repository: null
  sc: git
