branch-defaults:
  default:
    environment: aion-mainnet-node-prod-1
  feature/expanded-storage:
    environment: null
    group_suffix: null
  feature/multi-docker:
    environment: aion-mainnet-node-prod-1
  master:
    environment: aion-mastery-node-prod
  staging:
    environment: aion-mainnet-node-prod-1
global:
  application_name: aion-mainnet-node
  artifact: deploy.zip
  branch: master
  default_region: us-east-1
  repository: null
  sc: git
